version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.4-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: touch database/test.sqlite
      - run: php artisan migrate --env=testing
      - run: vendor/bin/phpunit
      - run: npm install
      - run: npm test
      - run: ./vendor/bin/phpcs --standard=phpcs.xml ./
      - run: ./vendor/bin/phpstan analyse

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "39:ef:c0:47:b7:84:98:3e:f5:60:a6:9a:2d:ce:68:87"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd docker-laravel/backend &&
      git pull origin main &&
      docker-compose exec app composer install &&
      docker-compose exec app npm install &&
      docker-compose exec app npm run prod &&
      docker-compose exec app php artisan migrate'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main