version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.4-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: touch database/test.sqlite
      - run: php artisan migrate --env=testing
      - run: ./vendor/bin/phpunit
      - run: npm install
      - run: npm test
      - run: ./vendor/bin/phpcs --standard=phpcs.xml ./
      - run: ./vendor/bin/phpstan analyse

  deploy:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "36:ed:62:82:1c:0a:8d:44:35:d5:97:c0:2f:da:67:ac"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd docker-laravel/backend && git pull origin main && docker-compose exec -T app composer install && docker-compose exec -T app npm install && docker-compose exec -T app npm run prod && docker-compose exec -T app php artisan migrate --force'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
        filters:
          branches:
            only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main